#open API
openapi: 3.0.3
info:
  title: PICSOU BANK Bot
  derciption: "this api manage one discord bank bot for RP servers in Discord"
  vertion: "1.0.0"
#server configuration
server:
  -url: '{protocol}://{server}'
  variables:
    protocol:
      enum:
        - http
        - https
      default: http
    serveur:
      defaults: localhost:8000
#differents tags of this project
tags:
  - name: contacts
    description: use accounts and transactions
  - name: partners
    decription: link two contacts 
  - name: account
    description: contains money of contacts
  - name: exchanges
    description: cash flows between accounts
  - name: automaticCashWithDrawal
    description: automatic transfers at regular intervals
  - name: accountsRights
    description: account access rights
paths:
  #contacts
  /contacts/login:
    post:
      tags:
        - contacts
      amountmary: Login as user
      requestBody:
        content:
          application/json:
            schema:
              required: [name, password]
              properties:
                name:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "connect sucessfully"
        "404":
          description: "User not found"
        "500":
          description: "Server ERROR"

  /contacts/register:
    post:
      tags:
        - contacts
      amountmary: Add new user
      requestBody:
        content:
          application/json:
            schema:
              required: [name, password, rôle]
              properties:
                  name:
                    type: string
                  password:
                    type: string
                  rôle:
                    type: string
                  partner_ids:
                    type: int []
      responses:
          "201":
            description: "OK"

  /contacts/contact:{id}:
    get: 
      tags:
        - contacts
      amountmary: Get a user by ID 
      operationId: getContactByID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: user fteched successfully
        "404":
          description: "NotFound"
    delete:
      tags:
        - contacts
      amountmary: Delete contact by id
      operation: delecteContactByID
      responses:
          "200":
            description: Contact deleted successfully
          "404":
            description: "NotFound"

  #partners
  /partner/add:
    post:
      tags:
        - partners
      amountmary: Add new partnership
      requestBody:
        content:
          application/json:
            schema:
              required: [contactID, contactPartnerID, contactRole, contactPartnerRole]
              properties:
                  contactID:
                    type: int
                  contactPartnerID:
                    type: int
                  contactRole:
                    type: string
                  contactPartnerRole:
                    type: string 
      responses:
        "201":
          description: "OK"

  /partner/contact:{contactID}:
    get: 
      tags:
        - partners
      amountmary: Get a partnership by contactID 
      operationId: getPartnerByContactID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: partnership fetched successfully
        "404":
          description: "NotFound"
    delete:
      tags:
        - partners
      amountmary: Delete partner by contactID
      operation: delectePartnerByContactID
      parameters:
        - $ref: '#/components/parameters/IdInPath'
      responses:
          "200":
            description: Partnership deleted successfully
            content:
              application/json:
                schema:
                  type: object
                  required: [ success ]
                  properties:
                    success:
                      type: boolean
                      example: true
                      default: true
          "404":
            description: "NotFound"

  /partner/contactPartner:{contactPartnerID}:
    get: 
      tags:
        - partners
      amountmary: Get a partnership by contactPartnerID 
      operationId: getPartnerByContactPartnerID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: partnership fetched successfully
        "404":
          description: "NotFound"
    delete:
      tags:
        - partners
      amountmary: Delete partner by contact partner id
      operationId: deletePartnerByContactPartnerId
      parameters:
        - $ref: '#/components/parameters/IdInPath'
      responses:
          "200":
            description: Partnership deleted successfully
            content:
              application/json:
                schema:
                  type: object
                  required: [ success ]
                  properties:
                    success:
                      type: boolean
                      example: true
                      default: true
          "404":
            description: "NotFound"

  /partners/partner:{id}:
    get: 
      tags:
        - partners
      amountmary: Get a partnership by ID 
      operationId: getPartnerByID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: partnership fetched successfully
        "404":
          description: "NotFound"
    delete:
      tags:
        - partners
      amountmary: Delete partner by id
      operationId: deletePartnerById
      parameters:
        - $ref: '#/components/parameters/IdInPath'
      responses:
          "200":
            description: Partnership deleted successfully
            content:
              application/json:
                schema:
                  type: object
                  required: [ success ]
                  properties:
                    success:
                      type: boolean
                      example: true
                      default: true
          "404":
            description: "NotFound"

  #accounts
  /accounts/{beneficiaryName}:
    get:
      amountmary: Récupérer les comptes par ID de bénéficiaire
      parameters:
        - name: beneficiaryName
          in: path
          description: ID du bénéficiaire
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    delete:
      amountmary: Supprimer les comptes par ID de bénéficiaire
      parameters:
        - name: beneficiaryName
          in: path
          description: ID du bénéficiaire
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succès

  /accounts/{id}:
    get:
      amountmary: Récupérer un compte par ID
      parameters:
        - name: id
          in: path
          description: ID du compte
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    delete:
      amountmary: Supprimer un compte par ID
      parameters:
        - name: id
          in: path
          description: ID du compte
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succès

  /accounts/login:
    post:
      amountmary: Se connecter à un compte
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [userId, id, password]
              properties:
                userId:
                  type: integer
                id:
                  type: integer
                password:
                  type: string
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
        '400':
          description: Identifiant ou mot de passe incorrect

  /accounts/add:
    post:
      amountmary: Ajouter un compte
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [beneficiaryName, password]
              properties:
                beneficiaryName:
                  type: integer
                password:
                  type: string
                balance:
                  type: number
      responses:
        '201':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  account:
                    $ref: '#/components/schemas/Account'
        '500':
          description: Erreur serveur

  /accounts/transaction:
    post:
      amountmary: Effectuer une transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [Id, userId, amount, type]
              properties:
                id:
                  type: integer
                userId:
                  type: integer
                amount:
                  type: number
                type:
                  type: string
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  change:
                    $ref: '#/components/schemas/Account'
        '400':
          description: Mauvaise requête

  /accounts/quickTransaction:
    post:
      amountmary: Effectuer une transaction rapide
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id, receiverId, userId, amount]
              properties:
                id:
                  type: integer
                receiverId:
                  type: integer
                userId:
                  type: integer
                amount:
                  type: number
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  exchange:
                    $ref: '#/components/schemas/Account'
        '400':
          description: Mauvaise requête

  #exchanges
  /exchanges:
    post:
      tags:
        - exchanges
      amountmary: Do one account transactions
      requestBody:
        content:
          application/json:
            schema:
              required: [yourid, yourpassword, receiverId, amount]
              properties:
                yourid:
                  type: int
                yourpassword:
                  type: string
                receiverId:
                  type: int
                amount:
                  type: float
      responses:
        "201":
          description: "OK"

  #automaticCashWithDrawal
  /automaticCashWithdrawal/add:
    post:
      tags:
        - automaticCashWithDrawal
      amountmary: automatic transactions
      requestBody:
        content:
          application/json:
            schema:
              required: [youridentifier, yourpassword, receiverIdentifier, amount, delay, delayUnit]
              properties:
                youridentifier:
                  type: string
                yourpassword:
                  type: string
                receiverIdentifier:
                  type: string
                amount:
                  type: float
                delayUnit:
                  type: int
                timeUnit:
                  type: string
                enddate:
                  type: string
                  format: date
      responses:
        "201":
          description: "OK"

  #accountRights
  /accountsRights/add:
    post:
      tags:
        - accountRights
      amountmary: access rights
      requestBody:
        content:
          application/json:
            schema:
              required: [userID, accountID, rights]
              properties:
                userID:
                  type: int
                accountID:
                  type: int
                rights:
                  type: string
      responses:
        "201":
          description: "OK"

  /accountsRights/user:{userID}&account:{accountID}:
    get:
      tags:
        - accountRights
      amountmary: get account rights
      operationId: getAccountRightsByUserIDAndAccountID
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: integer
        - name: accountID
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: rights fetched succesfully
        "404":
          description: rights not found
    delete:
      tags:
        - accountRights
      amountmary: delete rights
      operationId: deleteAccountRightsByUserIDAndAccountID
      parameters:
        -$ref: "#/components/parameters/idInPath"
      responses:
        "200":
          description: tights deleted succesfully
          content:
            application/json:
              schema:
                type: object
                required: [ success ]
                properties:
                  success:
                    type: boolean
                    example: true
                    default: true
        "404":
          $ref: "#/components/responses/NotFound"

#components
components:
  parameters:
    idInPath:
      required: true
      name: id
      in: path
      schema:
        type: integer
  schemas:
    AccountList:
      type: object
      properties:
        success:
          type: boolean
          default: true
          example: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/Accounts'
    Account:
      type: object
      properties:
        id:
          type: integer
          example: 1
        beneficiaryName:
          type: integer
          example: 1
        password:
          type: string
          example: "AzEr5t6-!Tp6"
        balance:
          type: number
          example: 1000
      required:
        - id
        - password
        - beneficiaryName
        - balance
  requestBodies:
    accountCreation:
      required: true
      decription: bank account thaat need to be created
      content:
        application/json:
          schema:
            required: [identifier, password, beneficiary_id]
            allof:
              - $ref: '#/components/schemas/Account'
  responses:
    RessourceCreated:
      description: "The ressource has been created"
      content:
        application/json:
          schema:
            type: objects
            required: [ success, id ]
            properties:
              success:
                type: boolean
                default: true
                example: true
              id:
                type: integer
                example: 1
                description: "The id of the ressource created"
    NotFound:
      description: "The resource specified is not found"
      content:
        application/json:
          schema:
            type: object
            required: [ success, message ]
            properties:
              success:
                type: boolean
                default: false
                example: false
              message:
                type: string
                default: ""
                example: "This ressource with this id is not found"
    InvalidBody:
      description: "The body sent to the request is invalid"
      content:
        application/json:
          schema:
            type: object
            required: [ success, message ]
            properties:
              success:
                type: boolean
                default: false
                example: false
              message:
                type: string
                default: ""
                example: "Please make sure that all args on the body are ok"
    InternalServerError:
      description: "An internal server error occurred"
      content:
        application/json:
          schema:
            type: object
            required: [ success, message ]
            properties:
              success:
                type: boolean
                default: false
                example: false
              message:
                type: string
                default: "An unknown server error occurred"
                example: "An unknown server error occurred"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Set your JWT token