#open API
openapi: 3.0.3
info:
  title: PICSOU BANK Bot
  description: "this api manage one discord bank bot for RP servers in Discord"
  version: "1.0.0"
#server configuration
paths:
  /accounts/{beneficiaryId}:
    get:
      summary: Récupérer les comptes par ID de bénéficiaire
      parameters:
        - name: beneficiaryId
          in: path
          description: ID du bénéficiaire
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    delete:
      summary: Supprimer les comptes par ID de bénéficiaire
      parameters:
        - name: beneficiaryId
          in: path
          description: ID du bénéficiaire
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succès

  /accounts/{id}:
    get:
      summary: Récupérer un compte par ID
      parameters:
        - name: id
          in: path
          description: ID du compte
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    delete:
      summary: Supprimer un compte par ID
      parameters:
        - name: id
          in: path
          description: ID du compte
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succès

  /accounts/login:
    post:
      summary: Se connecter à un compte
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                id:
                  type: integer
                password:
                  type: string
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
        '400':
          description: Identifiant ou mot de passe incorrect

  /accounts/add:
    post:
      summary: Ajouter un compte
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                beneficiaryId:
                  type: integer
                password:
                  type: string
                balance:
                  type: number
      responses:
        '201':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  account:
                    $ref: '#/components/schemas/Account'
        '500':
          description: Erreur serveur

  /accounts/transaction:
    post:
      summary: Effectuer une transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                userId:
                  type: integer
                sum:
                  type: number
                type:
                  type: string
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  change:
                    $ref: '#/components/schemas/Account'
        '400':
          description: Mauvaise requête

  /accounts/quickTransaction:
    post:
      summary: Effectuer une transaction rapide
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                cibleId:
                  type: integer
                userId:
                  type: integer
                sum:
                  type: number
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  exchange:
                    $ref: '#/components/schemas/Account'
        '400':
          description: Mauvaise requête

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
        beneficiaryId:
          type: integer
        balance:
          type: number
      required:
        - id
        - beneficiaryId
        - balance

